spring:
    datasource:
        password: root
        url: jdbc:postgresql://localhost:5432/empdb
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
management:
    endpoints:
        web:
            exposure:
                include: "health,metrics,info"